[package]
name = "localhost-proxy"
version = "0.1.0"
edition = "2024"
authors = ["Geoff Seemueller <28698553+geoffsee@users.noreply.github.com>"]

[[bin]]
name = "localhost-proxy"
path = "src/main.rs"

[dependencies]
axum = { version = "0.7.9", features = ["macros", "json", "query", "tracing"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "net"] }
reqwest = { version = "0.11.27", features = ["json", "rustls-tls"], default-features = false }
tower = { version = "0.5.2", features = ["tokio", "tracing"] }
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
http = "1.3.1"
bytes = "1.9.0"
thiserror = "1.0"
anyhow = "1.0"